LanchesMac/LanchesMac/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class ContatoController : Controller
    {
            public IActionResult Index()
            {
                return View();
            }
    }
}

LanchesMac/LanchesMac/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide marginTop1" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselLanches" data-slide-to="0" class="active"></li>
        <li data-target="#carouselLanches" data-slide-to="1"></li>
        <li data-target="#carouselLanches" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/carousel11.jpg" class="d-block w-100" alt="Lanche">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel12.jpg" class="d-block w-100" alt="Lanche">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel13.jpg" class="d-block w-100" alt="Lanche">
        </div>
    </div>
    <a class="left carousel-control" href="#carouselLanches" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carouselLanches" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>
  

LanchesMac/LanchesMac/Views/Shared/_Footer.cshtml
<footer>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
     <div class="container">
         <div class="row">
             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                 <h4> &copy; 2021 - LanchesMac</h4>
                 <p class="text-justify">
                     Aqui você encontra aquele lanche gostoso que da água na boca.
                     Aquela sobremesa saborosa e para acompanhar a sua bebida preferida.
                     E se você é vegetariano também vai encontrar o lanche, sobremesa e bebida do seu gosto.
                 </p>
             </div>

             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                 <h4>Tem alguma dúvida ?</h4>
                 <ul class="list-unstyled">
                     <li class="py-1"> Av. Bueno de Andrade, 56 Setor-2 Quadra-7</li>
                     <li class="py-1"> +55- 999 9123 502</li>
                     <li class="py-1"> <a href="lanchesmac@hotmail.com" style="color: yellow">lanchesmac@hotmail.com</a></li>
                 </ul>
             </div>
         </div>
     </div>
    </nav>
</footer>

LanchesMac/LanchesMac/Views/Shared/_LanchesResumo.cshtml
@model Lanche
   
        <div class="col-sm-4 col-md-4 col-lg-6">
            <img src="@Model.ImagemUrl" class="card-img-top imageLanche" alt="@Model.Nome" />
            <div class="figure-caption">
                <h4 class="formPullRightButton">@Model.Preco.ToString("c")</h4>
                <h4>
                    <a asp-controller="Lanche" asp-action="Details" asp-route-lancheId="@Model.LancheId">@Model.Nome</a>
                </h4>
                <h6>@Model.DescricaoCurta</h6>
            </div>
            <div text-right">
                <p class="formPullRightButton">
                    <a class="btn btn-primary" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheId="@Model.LancheId">
                        Incluir no Carrinho
                    </a>
                </p>
            </div>
        </div>

LanchesMac/LanchesMac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanchesMac</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo_lanche2-sfd.png" />
                    LanchesMac
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @await Component.InvokeAsync("CarrinhoCompraResumo");
                    }
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    @await Component.InvokeAsync("CategoriaMenu")
                    <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>

                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                    }
                    <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                        </div>
                    </form>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*<footer class="border-top footer text-muted">
        <div class="container">
                &copy; 2021 - LanchesMac
            </div>
    </footer>*@

    <partial name="_Footer"/>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>